"""SISITEMU — The Official Systems Programming Platform of the I Language."""

from __future__ import annotations

from sisitemu.ibikoresho_sisitemu import (
    Alignment,
    Allocator,
    ArenaAllocator,
    AtomicOps,
    BitManipulator,
    CacheManager,
    Endianness,
    MemoryBlock,
    MemoryRegion,
    Pointer,
    PoolAllocator,
    RegionAllocator,
    Slice,
    SystemsCore,
    get_systems_core,
)
from sisitemu.ibikorwa_sisitemu import (
    EnvironmentManager,
    IntervalTimer,
    ProcessInfo,
    ProcessManager,
    ProcessState,
    Scheduler,
    SchedulerPolicy,
    Signal,
    SignalManager,
    Timer,
    ThreadInfo,
    ThreadPriority,
)
from sisitemu.ububiko import (
    DirEntry,
    FATFileSystem,
    FileHandle,
    FilePermission,
    FileStat,
    FileSystem,
    FileType,
    MemoryFileSystem,
    NativeFileSystem,
    NullFS,
    OpenMode,
    VirtualFileSystem,
)
from sisitemu.itumanaho_sisitemu import (
    CANBus,
    Connection,
    DHCPClient,
    DNSResolver,
    HTTPRequest,
    HTTPResponse,
    HTTPServer,
    NetworkAddress,
    NetworkStack,
    Packet,
    Protocol,
    SerialPort,
    SocketState,
    SocketType,
    TCPServer,
    UDPEndpoint,
)
from sisitemu.ibyinjijwe import (
    ADCChannel,
    ADCController,
    Architecture,
    GPIOController,
    GPIOPin,
    HardwareTimer,
    I2CBus,
    I2CConfig,
    InterruptController,
    InterruptTrigger,
    MCU,
    MCUFamily,
    PWMController,
    PWMPin,
    PinMode,
    RTOS,
    SPIBus,
    SPIConfig,
    TimerConfig,
    UART,
    UARTConfig,
)
from sisitemu.umuyobora import (
    Driver,
    DriverManager,
    IPCChannel,
    Kernel,
    KernelState,
    KernelThread,
    PowerManager,
    PrivilegeLevel,
    Scheduler as KernelScheduler,
    SharedMemoryRegion,
    SyscallContext,
    SyscallNumber,
    VirtualMemoryManager,
)
from sisitemu.ibikoresho_byinjijwe import (
    DeviceClass,
    DeviceManager as DeviceDriverManager,
    DisplayDevice,
    GraphicsDevice,
    IndustrialController,
    PCIeController,
    PCIeDevice,
    PCIeDeviceClass,
    SensorDevice,
    StorageDevice,
    TouchDevice,
    USBController,
    USBDevice,
    USBDeviceClass,
)
from sisitemu.umutekano_sisitemu import (
    AuditLog,
    CipherAlgorithm,
    CryptographicEngine,
    HashAlgorithm,
    MemoryProtectionRegion,
    MemoryProtectionUnit,
    Sandbox,
    SandboxPolicy,
    SecureIPCChannel,
    SecurityLevel,
    SecurityManager,
    StackProtection,
)
from sisitemu.igenzura_sisitemu import (
    CrashDump,
    DebugLevel,
    Debugger,
    LiveDiagnostics,
    MemoryInspector,
    MemoryRegion as DebugMemoryRegion,
    ProfileSample,
    Profiler,
    TraceEvent,
    TracePoint,
    Tracer,
)
from sisitemu.imikorere_sisitemu import (
    Benchmark,
    BenchmarkResult,
    LatencyMeter,
    MemoryUsageTracker,
    PerformanceOptimizer,
    ThroughputMeter,
)
from sisitemu.itegeko_sisitemu import genda, register_subcommands

# New Infrastructure Modules
from sisitemu.ububiko_db import (
    BTreeIndex, BTreeNode, BufferPool, HashIndex, IsolationLevel,
    LSMTree, LogAction, MemTable, MemTableEntry, Page, Record,
    SSTable, SSTableBlock, StorageEngine, Transaction, TransactionManager,
    WALEntry, WriteAheadLog, IndexType,
)
from sisitemu.gukwirakwiza import (
    CRDTCounter, DistributedCounter, DistributedLock, LogEntry, LockRequest,
    Message, MessageQueue, RaftConfig, RaftConsensus, RaftRole, RPCHandler,
    RPCServer, ServiceDiscovery, ServiceInstance,
)
from sisitemu.ibicu import (
    Backend, CGroupConfig, ConfigEntry, ConfigManager, Container,
    ContainerImage, ContainerRuntime, ContainerState, Deployment,
    DeploymentStrategy, LBAlgorithm, LoadBalancer, NamespaceConfig,
    Orchestrator, Secret, SecretManager, VMState, VirtualMachine, VMManager,
)
from sisitemu.inkomoko import (
    DeviceType, EdgeDevice, EdgeRuntime, GPUVendor, GPUCompute, GPUDevice,
    IoTGateway, LowPowerManager, ModelServing, ModelSpec,
    Protocol as IoTProtocol,
    RTTask, RTTaskPriority, RealTimeController, TelemetryData, Tensor,
    TensorOps, TensorShape,
)
# GUI / Desktop Shell
from sisitemu.igaragaza import (
    Color, Compositor, CursorShape, Event, EventType, FontRenderer,
    Point, Rect, Theme, Window, WindowState,
)
from sisitemu.ibikoresho_bya_GUI import (
    Button, CheckBox, ComboBox, Container, DockStyle, GroupBox, Label,
    ListBox, Menu, MenuBar, MenuItem, Panel, ProgressBar, RadioButton,
    ScrollView, Slider, StatusBar, TabControl, TextBox, ToolTip,
    TreeView, VScrollBar, Widget,
)
from sisitemu.ikigoroba import (
    Desktop, DesktopIcon, SystemTray, Taskbar, TrayIcon,
)
# Extended module additions
from sisitemu.itumanaho_sisitemu import (
    DpdkBufferPool, DpdkForwarder, DpdkPort, DpdkPortStats,
    KernelBypassSocket, RdmaCompletionQueue, RdmaCompletionEntry,
    RdmaEndpoint, RdmaMemoryRegion, ZeroCopyBuffer,
)
from sisitemu.umuyobora import (
    CGroupManager, CGroupStats, ContainerIsolation, Namespace,
    NamespaceManager, Unikernel,
)
from sisitemu.ibyinjijwe import (
    DDS as DDSMiddleware, DDSQoS as DDSQoSVal,
    DDSWriter as DDSWriterVal, DDSReader as DDSReaderVal,
    DDSTopic as DDSTopicVal, DDSParticipant as DDSParticipantVal,
    RTController,
)
from sisitemu.ububiko import (
    AIOManager, AIORequest, IOURing, IOURingCQE, IOURingSQE,
    MMapFile,
)

__all__ = [
    # ibikoresho_sisitemu
    "Alignment",
    "Allocator",
    "ArenaAllocator",
    "AtomicOps",
    "BitManipulator",
    "CacheManager",
    "Endianness",
    "MemoryBlock",
    "MemoryRegion",
    "Pointer",
    "PoolAllocator",
    "RegionAllocator",
    "Slice",
    "SystemsCore",
    "get_systems_core",
    # ibikorwa_sisitemu
    "EnvironmentManager",
    "IntervalTimer",
    "ProcessInfo",
    "ProcessManager",
    "ProcessState",
    "Scheduler",
    "SchedulerPolicy",
    "Signal",
    "SignalManager",
    "Timer",
    "ThreadInfo",
    "ThreadPriority",
    # ububiko
    "DirEntry",
    "FATFileSystem",
    "FileHandle",
    "FilePermission",
    "FileStat",
    "FileSystem",
    "FileType",
    "MemoryFileSystem",
    "NativeFileSystem",
    "NullFS",
    "OpenMode",
    "VirtualFileSystem",
    # itumanaho_sisitemu
    "CANBus",
    "Connection",
    "DHCPClient",
    "DNSResolver",
    "HTTPRequest",
    "HTTPResponse",
    "HTTPServer",
    "NetworkAddress",
    "NetworkStack",
    "Packet",
    "Protocol",
    "SerialPort",
    "SocketState",
    "SocketType",
    "TCPServer",
    "UDPEndpoint",
    # ibyinjijwe
    "ADCChannel",
    "ADCController",
    "Architecture",
    "GPIOController",
    "GPIOPin",
    "HardwareTimer",
    "I2CBus",
    "I2CConfig",
    "InterruptController",
    "InterruptTrigger",
    "MCU",
    "MCUFamily",
    "PWMController",
    "PWMPin",
    "PinMode",
    "RTOS",
    "SPIBus",
    "SPIConfig",
    "TimerConfig",
    "UART",
    "UARTConfig",
    # umuyobora
    "Driver",
    "DriverManager",
    "IPCChannel",
    "Kernel",
    "KernelState",
    "KernelThread",
    "KernelScheduler",
    "PowerManager",
    "PrivilegeLevel",
    "SharedMemoryRegion",
    "SyscallContext",
    "SyscallNumber",
    "VirtualMemoryManager",
    # ibikoresho_byinjijwe
    "DeviceClass",
    "DeviceDriverManager",
    "DisplayDevice",
    "GraphicsDevice",
    "IndustrialController",
    "PCIeController",
    "PCIeDevice",
    "PCIeDeviceClass",
    "SensorDevice",
    "StorageDevice",
    "TouchDevice",
    "USBController",
    "USBDevice",
    "USBDeviceClass",
    # umutekano_sisitemu
    "AuditLog",
    "CipherAlgorithm",
    "CryptographicEngine",
    "HashAlgorithm",
    "MemoryProtectionRegion",
    "MemoryProtectionUnit",
    "Sandbox",
    "SandboxPolicy",
    "SecureIPCChannel",
    "SecurityLevel",
    "SecurityManager",
    "StackProtection",
    # igenzura_sisitemu
    "CrashDump",
    "DebugLevel",
    "Debugger",
    "LiveDiagnostics",
    "MemoryInspector",
    "DebugMemoryRegion",
    "ProfileSample",
    "Profiler",
    "TraceEvent",
    "TracePoint",
    "Tracer",
    # imikorere_sisitemu
    "Benchmark",
    "BenchmarkResult",
    "LatencyMeter",
    "MemoryUsageTracker",
    "PerformanceOptimizer",
    "ThroughputMeter",
    # itegeko_sisitemu
    "genda",
    "register_subcommands",
    # ububiko_db
    "BTreeIndex", "BTreeNode", "BufferPool", "HashIndex", "IsolationLevel",
    "LSMTree", "LogAction", "MemTable", "MemTableEntry", "Page", "Record",
    "SSTable", "SSTableBlock", "StorageEngine", "Transaction", "TransactionManager",
    "WALEntry", "WriteAheadLog", "IndexType",
    # gukwirakwiza
    "CRDTCounter", "DistributedCounter", "DistributedLock", "LockRequest",
    "LogEntry", "Message", "MessageQueue", "RaftConfig", "RaftConsensus",
    "RaftRole", "RPCHandler", "RPCServer", "ServiceDiscovery", "ServiceInstance",
    # ibicu
    "Backend", "CGroupConfig", "ConfigEntry", "ConfigManager", "Container",
    "ContainerImage", "ContainerRuntime", "ContainerState", "Deployment",
    "DeploymentStrategy", "LBAlgorithm", "LoadBalancer", "NamespaceConfig",
    "Orchestrator", "Secret", "SecretManager", "VMState", "VirtualMachine", "VMManager",
    # inkomoko
    "DeviceType", "EdgeDevice", "EdgeRuntime", "GPUVendor", "GPUCompute", "GPUDevice",
    "IoTGateway", "LowPowerManager", "ModelServing", "ModelSpec", "IoTProtocol",
    "RTTask", "RTTaskPriority", "RealTimeController", "TelemetryData", "Tensor",
    "TensorOps", "TensorShape",
    # Extended networking (RDMA/DPDK/zero-copy)
    "DpdkBufferPool", "DpdkForwarder", "DpdkPort", "DpdkPortStats",
    "KernelBypassSocket", "RdmaCompletionQueue", "RdmaCompletionEntry",
    "RdmaEndpoint", "RdmaMemoryRegion", "ZeroCopyBuffer",
    # Extended kernel (containers/unikernel)
    "CGroupManager", "CGroupStats", "ContainerIsolation", "Namespace",
    "NamespaceManager", "Unikernel",
    # Extended embedded (DDS, RT)
    "DDSMiddleware", "DDSQoSVal", "DDSWriterVal", "DDSReaderVal",
    "DDSTopicVal", "DDSParticipantVal", "RTController",
    # Extended filesystem (mmap, aio, io_uring)
    "AIOManager", "AIORequest", "IOURing", "IOURingCQE", "IOURingSQE", "MMapFile",
    # igaragaza (display server / compositor)
    "Color", "Compositor", "CursorShape", "Event", "EventType", "FontRenderer",
    "Point", "Rect", "Theme", "Window", "WindowState",
    # ibikoresho_bya_GUI (widget toolkit)
    "Button", "CheckBox", "ComboBox", "Container", "DockStyle", "GroupBox", "Label",
    "ListBox", "Menu", "MenuBar", "MenuItem", "Panel", "ProgressBar", "RadioButton",
    "ScrollView", "Slider", "StatusBar", "TabControl", "TextBox", "ToolTip",
    "TreeView", "VScrollBar", "Widget",
    # ikigoroba (desktop shell)
    "Desktop", "DesktopIcon", "SystemTray", "Taskbar", "TrayIcon",
]
