"""admin — Admin dashboard scaffolding generator.

Produces admin panel configuration, list/detail/edit views,
filter definitions, and action handlers from a CanonicalModel.
"""

from __future__ import annotations

from typing import Dict, List

from ububiko.ihuriro.ibyara import BaseGenerator
from ububiko.ihuriro.ihuriro import CanonicalField, CanonicalModel


def _display_fields(model: CanonicalModel) -> List[str]:
    """Select fields suitable for list display."""
    excluded = {"password", "blob", "json", "text"}
    candidates = []
    preferred = [f for f in model.fields.values()
                 if f.primary_key or f.name in ("name", "title", "email", "code")]
    if preferred:
        candidates.extend(preferred)
    candidates.extend(
        f for f in model.fields.values()
        if f.native_type not in excluded and f not in candidates
    )
    return [f.name for f in candidates[:6]]


def _filter_fields(model: CanonicalModel) -> List[str]:
    return [f.name for f in model.fields.values()
            if f.indexed or f.unique or f.native_type == "boolean"
            or f.name in ("status", "active", "category_id", "type")]


class AdminGenerator(BaseGenerator):
    """Generates admin dashboard configuration."""

    target_name = "admin"

    @classmethod
    def generate(cls, model: CanonicalModel) -> Dict[str, str]:
        base_name = model.table_name
        class_name = model.name
        display = _display_fields(model)
        filters = _filter_fields(model)

        content = (
            f'"""Admin configuration for {class_name}.\n\n'
            f"Auto-generated by IHuriro.\n"
            f'"""\n\n'
            f"from typing import Any, Dict, List\n\n\n"
            f"ADMIN_CONFIG = {{\n"
            f'    "model": "{class_name}",\n'
            f'    "table": "{base_name}",\n'
            f'    "label": "{class_name.replace(chr(95), chr(32)).title()}",\n'
            f'    "label_plural": "{class_name.replace(chr(95), chr(32)).title()}s",\n'
            f'    "icon": "database",\n'
            f'    "list_display": {display!r},\n'
            f'    "list_filter": {filters!r},\n'
            f'    "search_fields": {[f.name for f in model.fields.values() if f.indexed or f.native_type in ("string", "email", "text")][:3]!r},\n'
            f'    "sortable": {[f.name for f in model.fields.values() if not f.relation or f.relation == "belongs_to"][:5]!r},\n'
            f'    "readonly_fields": {[f.name for f in model.fields.values() if f.read_only or f.auto_increment]!r},\n'
            f'    "audit_fields": {model.audit_fields},\n'
            f'    "soft_delete": {model.soft_delete},\n'
            f"}}\n\n\n"
            f"class {class_name}Admin:\n"
            f'    """Admin panel configuration for {class_name}."""\n\n'
            f"    config = ADMIN_CONFIG\n\n"
            f"    @staticmethod\n"
            f"    def get_list_columns() -> List[str]:\n"
            f"        return {display!r}\n\n"
            f"    @staticmethod\n"
            f"    def get_filter_fields() -> List[str]:\n"
            f"        return {filters!r}\n\n"
            f"    @staticmethod\n"
            f"    def get_actions() -> List[Dict[str, str]]:\n"
            f"        return [\n"
            f'            {{"name": "export_csv", "label": "Export CSV"}},\n'
            f'            {{"name": "duplicate", "label": "Duplicate"}},\n'
            f"        ]\n"
        )

        return {f"admin_{base_name}.py": content}
