"""amakubi — Database schema and migration generator.

Produces CREATE TABLE SQL, migration class files, and index definitions
from a CanonicalModel.
"""

from __future__ import annotations

from datetime import datetime
from typing import Dict, List

from ububiko.ihuriro.ibyara import BaseGenerator
from ububiko.ihuriro.ihuriro import CanonicalField, CanonicalModel


def _sql_type(field: CanonicalField) -> str:
    mapping = {
        "integer": "INTEGER",
        "float": "REAL",
        "decimal": "DECIMAL",
        "boolean": "BOOLEAN",
        "string": f"VARCHAR({field.max_length or 255})",
        "text": "TEXT",
        "datetime": "TIMESTAMP",
        "date": "DATE",
        "time": "TIME",
        "blob": "BLOB",
        "uuid": "UUID",
        "json": "JSON",
        "array": "JSON",
        "email": f"VARCHAR({field.max_length or 255})",
        "url": f"VARCHAR({field.max_length or 2048})",
        "password": f"VARCHAR({field.max_length or 255})",
        "relation": "INTEGER",
    }
    base = mapping.get(field.native_type, "TEXT")
    if field.native_type == "decimal":
        prec = field.precision or 10
        scale = field.scale or 2
        base = f"DECIMAL({prec}, {scale})"
    return base


def _col_sql(field: CanonicalField) -> str:
    parts = [field.name, _sql_type(field)]
    if field.primary_key:
        parts.append("PRIMARY KEY")
    if field.auto_increment:
        parts.append("AUTOINCREMENT" if "SQLite" in str(type(None)) else "AUTO_INCREMENT")
    if field.unique:
        parts.append("UNIQUE")
    if not field.required:
        parts.append("NOT NULL")
    if field.default is not None:
        if isinstance(field.default, str):
            parts.append(f"DEFAULT '{field.default}'")
        else:
            parts.append(f"DEFAULT {field.default}")
    if field.foreign_key:
        parts.append(f"REFERENCES {field.foreign_key}")
    return " ".join(parts)


class DatabaseGenerator(BaseGenerator):
    """Generates SQL DDL and migration files."""

    target_name = "database"

    @classmethod
    def generate(cls, model: CanonicalModel) -> Dict[str, str]:
        files: Dict[str, str] = {}
        base_name = model.table_name

        # CREATE TABLE SQL
        col_defs = []
        for f in model.fields.values():
            if f.relation and f.relation in ("has_many", "has_one"):
                continue
            col_defs.append(f"  {_col_sql(f)}")
        if model.audit_fields:
            col_defs.append("  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP")
            col_defs.append("  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP")
        if model.soft_delete:
            col_defs.append("  deleted_at TIMESTAMP")

        indexes = []
        for f in model.fields.values():
            if f.indexed and not f.primary_key and not f.unique:
                idx_name = f"idx_{base_name}_{f.name}"
                indexes.append(f"CREATE INDEX IF NOT EXISTS {idx_name} ON {base_name} ({f.name});")
        for idx in model.indexes:
            idx_name = idx.name or f"idx_{base_name}_{'_'.join(idx.columns)}"
            unique = "UNIQUE " if idx.unique else ""
            cols = ", ".join(idx.columns)
            indexes.append(f"CREATE {unique}INDEX IF NOT EXISTS {idx_name} ON {base_name} ({cols});")

        sql = (
            f"-- Table: {base_name} (generated by IHuriro)\n"
            f"-- Model: {model.name}\n\n"
            f"CREATE TABLE IF NOT EXISTS {base_name} (\n"
            + ",\n".join(col_defs) +
            "\n);\n\n"
            + "\n".join(indexes)
        )
        files[f"{base_name}.sql"] = sql

        # Migration Python file
        version = datetime.utcnow().strftime("%Y%m%d%H%M%S")
        mig_content = (
            f'"""Migration: create_{base_name}\n\n'
            f"Auto-generated by IHuriro from {model.name}\n"
            f'"""\n\n'
            f"from ububiko.imuka import Migration, MigrationEngine\n\n\n"
            f"class Create{model.name}(Migration):\n"
            f'    """Create the {base_name} table."""\n\n'
            f'    version = "{version}"\n'
            f'    description = "create_{base_name}"\n\n'
            f"    def up(self, engine: MigrationEngine) -> None:\n"
            f'        engine.execute("""{sql.replace(chr(34), chr(39) + chr(34) + chr(39))}""", {{}})\n\n'
            f"    def down(self, engine: MigrationEngine) -> None:\n"
            f'        engine.execute("DROP TABLE IF EXISTS {base_name}", {{}})\n'
        )
        files[f"{version}_create_{base_name}.py"] = mig_content

        return files
