"""graphql — GraphQL schema generator.

Produces GraphQL type definitions, query fields, mutation fields,
and resolver stubs from a CanonicalModel.
"""

from __future__ import annotations

from typing import Dict, List

from ububiko.ihuriro.ibyara import BaseGenerator
from ububiko.ihuriro.ihuriro import CanonicalField, CanonicalModel


def _gql_type(field: CanonicalField) -> str:
    mapping = {
        "string": "String", "integer": "Int", "float": "Float",
        "boolean": "Boolean", "datetime": "DateTime", "date": "Date",
        "uuid": "ID", "text": "String", "email": "String", "url": "String",
        "password": "String", "json": "JSON", "array": "[String]",
        "decimal": "Float", "relation": "Int", "blob": "String",
    }
    gtype = mapping.get(field.native_type, "String")
    if not field.required and not field.primary_key:
        return gtype
    return f"{gtype}!"


class GraphQLGenerator(BaseGenerator):
    """Generates GraphQL schema definitions and resolver stubs."""

    target_name = "graphql"

    @classmethod
    def generate(cls, model: CanonicalModel) -> Dict[str, str]:
        base_name = model.table_name
        class_name = model.name

        # Type definition
        field_defs = []
        for f in model.fields.values():
            if f.relation and f.relation in ("has_many", "has_one"):
                target_type = f.target_entity or "Unknown"
                field_defs.append(f"  {f.name}: [{target_type}]")
            else:
                field_defs.append(f"  {f.name}: {_gql_type(f)}")

        type_def = (
            f'"""GraphQL schema for {class_name}.\n\n'
            f"Auto-generated by IHuriro.\n"
            f'"""\n\n'
            f"type {class_name} {{\n"
            + "\n".join(field_defs) +
            "\n}\n"
        )

        # Input type
        input_fields = []
        for f in model.fields.values():
            if f.primary_key or f.read_only or f.auto_increment:
                continue
            if f.relation and f.relation in ("has_many", "has_one", "many_to_many"):
                continue
            gtype = _gql_type(f).rstrip("!")
            input_fields.append(f"  {f.name}: {gtype}")

        input_def = (
            f"input {class_name}Input {{\n"
            + "\n".join(input_fields) +
            "\n}\n"
        )

        # Queries & Mutations
        pk_field = model.pk_field
        pk_name = pk_field.name if pk_field else "id"

        queries = (
            f"extend type Query {{\n"
            f"  {base_name}({pk_name}: ID!): {class_name}\n"
            f"  {base_name}List(page: Int = 1, limit: Int = 20): [{class_name}]\n"
            f"}}\n"
        )

        mutations = (
            f"extend type Mutation {{\n"
            f"  create{class_name}(input: {class_name}Input!): {class_name}\n"
            f"  update{class_name}({pk_name}: ID!, input: {class_name}Input!): {class_name}\n"
            f"  delete{class_name}({pk_name}: ID!): Boolean\n"
            f"}}\n"
        )

        # Resolver stubs
        resolvers = (
            f"# Resolver stubs for {class_name}\n"
            f"#\n"
            f"# def resolve_{base_name}(root, info, {pk_name}):\n"
            f"#     return db.query({class_name}).get({pk_name})\n"
            f"#\n"
            f"# def resolve_{base_name}_list(root, info, page=1, limit=20):\n"
            f"#     offset = (page - 1) * limit\n"
            f"#     return db.query({class_name}).offset(offset).limit(limit).all()\n"
        )

        schema_content = type_def + "\n" + input_def + "\n" + queries + "\n" + mutations
        resolver_content = resolvers

        return {
            f"{base_name}.graphql": schema_content,
            f"{base_name}_resolvers.py": resolver_content,
        }
