"""ifishi — Form definition generator.

Produces form field definitions, HTML form templates, validation
integration, and UI component configurations from a CanonicalModel.
"""

from __future__ import annotations

from typing import Dict, List

from ububiko.ihuriro.ibyara import BaseGenerator
from ububiko.ihuriro.ihuriro import CanonicalField, CanonicalModel


def _widget(field: CanonicalField) -> str:
    explicit = field.widget
    if explicit:
        return explicit
    mapping = {
        "string": "text", "integer": "number", "float": "number",
        "boolean": "checkbox", "datetime": "datetime-local",
        "date": "date", "time": "time", "text": "textarea",
        "email": "email", "url": "url", "password": "password",
        "array": "select", "json": "textarea",
        "decimal": "number", "relation": "select",
    }
    return mapping.get(field.native_type, "text")


def _html_input(field: CanonicalField, name_prefix: str = "") -> str:
    field_name = f"{name_prefix}{field.name}"
    w = _widget(field)
    required = " required" if field.required and not field.primary_key else ""
    placeholder = f' placeholder="{field.description}"' if field.description else ""
    label = field.name.replace("_", " ").title()

    if w == "textarea":
        return (
            f'  <div class="form-group">\n'
            f'    <label for="{field_name}">{label}</label>\n'
            f'    <textarea id="{field_name}" name="{field_name}"{required}{placeholder}></textarea>\n'
            f'  </div>'
        )
    elif w == "checkbox":
        return (
            f'  <div class="form-group form-check">\n'
            f'    <input type="checkbox" id="{field_name}" name="{field_name}"{placeholder}>\n'
            f'    <label for="{field_name}">{label}</label>\n'
            f'  </div>'
        )
    elif w == "select":
        options = ""
        for val, lbl in field.choices:
            options += f'      <option value="{val}">{lbl}</option>\n'
        return (
            f'  <div class="form-group">\n'
            f'    <label for="{field_name}">{label}</label>\n'
            f'    <select id="{field_name}" name="{field_name}"{required}>\n'
            f'{options}    </select>\n'
            f'  </div>'
        )
    else:
        input_type = w
        return (
            f'  <div class="form-group">\n'
            f'    <label for="{field_name}">{label}</label>\n'
            f'    <input type="{input_type}" id="{field_name}" name="{field_name}"{required}{placeholder}>\n'
            f'  </div>'
        )


class FormGenerator(BaseGenerator):
    """Generates HTML form definitions and UI form configs."""

    target_name = "forms"

    @classmethod
    def generate(cls, model: CanonicalModel) -> Dict[str, str]:
        base_name = model.table_name
        class_name = model.name

        # I Language form config
        form_config = (
            f'/// Form configuration for {class_name}\n'
            f"/// Auto-generated by IHuriro\n\n"
            f"pub form {class_name}Form {{\n"
        )
        for f in model.fields.values():
            if f.primary_key or f.auto_increment:
                continue
            readonly = "readonly" if f.read_only else ""
            form_config += (
                f'    {f.name}: {_widget(f)}'
                f'{" required" if f.required else ""}'
                f'{" " + readonly if readonly else ""}'
                f',\n'
            )
        form_config += "}\n"

        # HTML form
        html_fields = "\n\n".join(
            _html_input(f) for f in model.fields.values()
            if not f.primary_key and not f.auto_increment
        )

        html = (
            f'<!-- Form for {class_name} -->\n'
            f'<!-- Auto-generated by IHuriro -->\n\n'
            f'<form id="{base_name}-form" method="POST" action="/api/{base_name}">\n'
            f'{html_fields}\n\n'
            f'  <div class="form-actions">\n'
            f'    <button type="submit">Save</button>\n'
            f'    <button type="reset">Reset</button>\n'
            f'  </div>\n'
            f'</form>\n'
        )

        return {
            f"{base_name}.form.i": form_config,
            f"{base_name}.html": html,
        }
