"""ikizamini — Test data generator.

Produces Faker-based data generators, factory definitions,
seed scripts, and test fixtures from a CanonicalModel.
"""

from __future__ import annotations

import json
from typing import Any, Dict, List, Optional

from ububiko.ihuriro.ibyara import BaseGenerator
from ububiko.ihuriro.ihuriro import CanonicalField, CanonicalModel


def _faker_method(field: CanonicalField) -> str:
    """Return a Faker method that generates appropriate test data."""
    mapping: Dict[str, str] = {
        "name": "faker.name()",
        "title": "faker.catch_phrase()",
        "first_name": "faker.first_name()",
        "last_name": "faker.last_name()",
        "email": "faker.email()",
        "phone": "faker.phone_number()",
        "address": "faker.address()",
        "city": "faker.city()",
        "country": "faker.country()",
        "zip": "faker.zipcode()",
        "description": "faker.text(max_nb_chars=200)",
        "content": "faker.paragraph(nb_sentences=5)",
        "summary": "faker.sentence()",
        "bio": "faker.text(max_nb_chars=500)",
        "url": "faker.url()",
        "avatar": "faker.image_url()",
        "ip": "faker.ipv4()",
        "color": "faker.hex_color()",
        "price": "round(random.uniform(1.0, 999.99), 2)",
        "quantity": "random.randint(0, 1000)",
        "age": "random.randint(18, 99)",
        "score": "random.randint(0, 100)",
        "status": "random.choice(['active', 'inactive', 'pending'])",
        "type": "random.choice(['standard', 'premium', 'basic'])",
        "role": "random.choice(['admin', 'user', 'viewer'])",
        "language": "random.choice(['rw', 'en', 'fr'])",
        "currency": "random.choice(['RWF', 'USD', 'EUR'])",
    }

    field_name = field.name.lower()
    for pattern, method in mapping.items():
        if pattern in field_name:
            return method

    type_gen = {
        "string": "faker.word()",
        "integer": "random.randint(1, 10000)",
        "float": "round(random.uniform(0.0, 1000.0), 2)",
        "boolean": "random.choice([True, False])",
        "datetime": "faker.date_time_this_year().isoformat()",
        "date": "faker.date_this_year().isoformat()",
        "text": "faker.paragraph()",
        "email": "faker.email()",
        "url": "faker.url()",
        "uuid": "str(uuid.uuid4())",
        "password": "faker.password()",
        "decimal": "round(random.uniform(0.0, 10000.0), 2)",
        "json": "{}",
        "array": "[]",
        "relation": "random.randint(1, 100)",
    }
    return type_gen.get(field.native_type, "faker.word()")


class TestDataGenerator(BaseGenerator):
    """Generates test data factories and seed scripts."""

    target_name = "test_data"

    @classmethod
    def generate(cls, model: CanonicalModel) -> Dict[str, str]:
        base_name = model.table_name
        class_name = model.name

        generator_methods = []
        for f in model.fields.values():
            if f.primary_key and f.auto_increment:
                continue
            if f.relation and f.relation in ("has_many", "has_one", "many_to_many"):
                continue
            method = _faker_method(f)
            generator_methods.append(f"        '{f.name}': {method},")

        gen_body = "\n".join(generator_methods)

        # Python factory
        factory = (
            f'"""Test data factory for {class_name}.\n\n'
            f"Auto-generated by IHuriro.\n"
            f'"""\n\n'
            f"import random\n"
            f"import uuid\n"
            f"from typing import Any, Dict, List, Optional\n\n\n"
            f"try:\n"
            f"    from faker import Faker\n"
            f"    faker = Faker()\n"
            f"except ImportError:\n"
            f"    import warnings\n"
            f"    warnings.warn('faker not installed; using basic random generators')\n"
            f"    class _Faker:\n"
            f"        @staticmethod\n"
            f"        def name(): return 'Test User'\n"
            f"        @staticmethod\n"
            f"        def email(): return 'test@example.com'\n"
            f"        @staticmethod\n"
            f"        def word(): return 'test'\n"
            f"        @staticmethod\n"
            f"        def sentence(): return 'Test sentence.'\n"
            f"        @staticmethod\n"
            f"        def paragraph(): return 'Test paragraph.'\n"
            f"        @staticmethod\n"
            f"        def url(): return 'https://example.com'\n"
            f"        @staticmethod\n"
            f"        def date_time_this_year(): return __import__('datetime').datetime.utcnow()\n"
            f"        @staticmethod\n"
            f"        def date_this_year(): return __import__('datetime').date.today()\n"
            f"        @staticmethod\n"
            f"        def password(): return 'testpass123'\n"
            f"        @staticmethod\n"
            f"        def phone_number(): return '+250-700-000-000'\n"
            f"        @staticmethod\n"
            f"        def address(): return 'Kigali, Rwanda'\n"
            f"        @staticmethod\n"
            f"        def city(): return 'Kigali'\n"
            f"        @staticmethod\n"
            f"        def country(): return 'Rwanda'\n"
            f"        @staticmethod\n"
            f"        def zipcode(): return '00000'\n"
            f"        @staticmethod\n"
            f"        def image_url(): return 'https://example.com/img.png'\n"
            f"        @staticmethod\n"
            f"        def ipv4(): return '127.0.0.1'\n"
            f"        @staticmethod\n"
            f"        def hex_color(): return '#000000'\n"
            f"        @staticmethod\n"
            f"        def catch_phrase(): return 'Test Phrase'\n"
            f"        @staticmethod\n"
            f"        def text(max_nb_chars=200): return 'Test text.'\n"
            f"    faker = _Faker()\n\n\n"
            f"def generate_{base_name}(**overrides: Any) -> Dict[str, Any]:\n"
            f'    """Generate a single {class_name} record dict."""\n'
            f"    data = {{\n"
            f"{gen_body}\n"
            f"    }}\n"
            f"    data.update(overrides)\n"
            f"    return data\n\n\n"
            f"def generate_many_{base_name}(count: int = 10, **overrides: Any) -> List[Dict[str, Any]]:\n"
            f'    """Generate multiple {class_name} record dicts."""\n'
            f"    return [generate_{base_name}(**overrides) for _ in range(count)]\n\n\n"
            f"def seed_{base_name}(adapter: Any, count: int = 10) -> int:\n"
            f'    """Insert generated {class_name} records into the database."""\n'
            f"    records = generate_many_{base_name}(count)\n"
            f"    for record in records:\n"
            f"        adapter.execute(\n"
            f'            "INSERT INTO {base_name} ({", ".join(f.name for f in model.fields.values() if not f.primary_key or not f.auto_increment)}) "\n'
            f'            "VALUES ({", ".join(":" + f.name for f in model.fields.values() if not f.primary_key or not f.auto_increment)})",\n'
            f"            record,\n"
            f"        )\n"
            f"    return len(records)\n"
        )

        return {f"factory_{base_name}.py": factory}
