"""kugenzura — Validation rules generator.

Produces Python validation functions, constraint definitions,
and JSON Schema validation rules from a CanonicalModel.
"""

from __future__ import annotations

from typing import Dict, List

from ububiko.ihuriro.ibyara import BaseGenerator
from ububiko.ihuriro.ihuriro import CanonicalField, CanonicalModel


def _validation_code(field: CanonicalField, var_name: str = "data") -> List[str]:
    rules = []
    val = f"{var_name}.get('{field.name}')"
    if field.required and not field.primary_key:
        rules.append(f"    if not {val} and {val} is not None:\n"
                     f"        errors['{field.name}'].append('This field is required.')")
    if field.native_type in ("string", "email", "url", "password", "text"):
        if field.max_length:
            rules.append(f"    if {val} and len({val}) > {field.max_length}:\n"
                         f"        errors['{field.name}']"
                         f".append('Must be at most {field.max_length} characters.')")
    if field.native_type == "email":
        rules.append(f"    if {val} and '@' not in {val}:\n"
                     f"        errors['{field.name}'].append('Invalid email address.')")
    if field.native_type == "url":
        rules.append(f"    if {val} and not {val}.startswith(('http://', 'https://')):\n"
                     f"        errors['{field.name}'].append('Invalid URL.')")
    if field.native_type in ("integer", "float", "decimal"):
        if field.min_value is not None:
            rules.append(f"    if {val} is not None and {val} < {field.min_value}:\n"
                         f"        errors['{field.name}']"
                         f".append('Must be at least {field.min_value}.')")
        if field.max_value is not None:
            rules.append(f"    if {val} is not None and {val} > {field.max_value}:\n"
                         f"        errors['{field.name}']"
                         f".append('Must be at most {field.max_value}.')")
    if field.unique:
        rules.append(f"    # TODO: check uniqueness of '{field.name}' in database")
    if field.choices:
        choices_str = ", ".join(repr(c[0]) for c in field.choices)
        rules.append(f"    if {val} is not None and {val} not in [{choices_str}]:\n"
                     f"        errors['{field.name}'].append('Invalid choice.')")
    if field.secret:
        rules.append(f"    if {val} and len({val}) < 8:\n"
                     f"        errors['{field.name}'].append('Must be at least 8 characters.')")
    return rules


class ValidationGenerator(BaseGenerator):
    """Generates Python validation module."""

    target_name = "validation"

    @classmethod
    def generate(cls, model: CanonicalModel) -> Dict[str, str]:
        base_name = model.table_name
        class_name = model.name

        rules = []
        for f in model.fields.values():
            rules.extend(_validation_code(f))

        rules_code = "\n".join(rules) if rules else "    pass"

        content = (
            f'"""Validation rules for {class_name}.\n\n'
            f"Auto-generated by IHuriro.\n"
            f'"""\n\n'
            f"from typing import Any, Dict, List\n\n\n"
            f"def validate_{base_name}(data: Dict[str, Any]) -> Dict[str, List[str]]:\n"
            f'    """Validate {base_name} data and return errors dict."""\n'
            f"    errors: Dict[str, List[str]] = {{}}\n"
            f"    for field_name in {list(model.fields.keys())!r}:\n"
            f"        errors[field_name] = []\n"
            f"{rules_code}\n"
            f"    return {{k: v for k, v in errors.items() if v}}\n\n\n"
            f"def is_valid_{base_name}(data: Dict[str, Any]) -> bool:\n"
            f'    """Check if {base_name} data is valid."""\n'
            f"    return len(validate_{base_name}(data)) == 0\n"
        )

        return {f"validate_{base_name}.py": content}
