"""rest — REST API contract generator.

Produces FastAPI/UFA route definitions, CRUD endpoint handlers,
OpenAPI operation metadata, and URL routing from a CanonicalModel.
"""

from __future__ import annotations

from typing import Dict, List

from ububiko.ihuriro.ibyara import BaseGenerator
from ububiko.ihuriro.ihuriro import CanonicalField, CanonicalModel


def _field_imports(model: CanonicalModel) -> str:
    needs_optional = any(not f.required for f in model.fields.values())
    needs_list = any(f.native_type == "array" for f in model.fields.values())
    imports = ["from typing import Any, Dict, List, Optional"]
    imports.append("from pydantic import BaseModel, Field")
    imports.append("from datetime import datetime")
    return "\n".join(imports)


def _field_to_pydantic(field: CanonicalField) -> str:
    type_map = {
        "string": "str", "integer": "int", "float": "float",
        "boolean": "bool", "datetime": "datetime", "date": "str",
        "uuid": "str", "text": "str", "email": "str", "url": "str",
        "password": "str", "json": "Dict[str, Any]", "array": "List[Any]",
        "decimal": "float", "relation": "int", "blob": "str",
    }
    py_type = type_map.get(field.native_type, "Any")
    if not field.required and not field.primary_key:
        py_type = f"Optional[{py_type}]"
    default = f" = Field(default={field.default!r})" if field.default is not None else ""
    description = f', description="{field.description}"' if field.description else ""
    return f"    {field.name}: {py_type}{default}{description}"


class RestApiGenerator(BaseGenerator):
    """Generates FastAPI/UFA REST API endpoints."""

    target_name = "rest_api"

    @classmethod
    def generate(cls, model: CanonicalModel) -> Dict[str, str]:
        base_name = model.table_name
        class_name = model.name
        pk = model.pk_field
        pk_name = pk.name if pk else "id"

        schema_fields = "\n".join(_field_to_pydantic(f) for f in model.fields.values()
                                  if not f.relation or f.relation == "belongs_to")
        create_fields = "\n".join(
            f"    {f.name}: {'Optional[' if not f.required else ''}{_type(f)}{']' if not f.required else ''}"
            for f in model.fields.values()
            if not f.primary_key and not f.read_only
            and (not f.relation or f.relation == "belongs_to")
        )

        content = (
            f'"""REST API for {class_name}.\n\n'
            f"Auto-generated by IHuriro.\n"
            f'"""\n\n'
            f"{_field_imports(model)}\n\n\n"
            f"class {class_name}Schema(BaseModel):\n"
            f'    """Pydantic schema for {class_name}."""\n\n'
            f"{schema_fields}\n\n"
            f"    class Config:\n"
            f"        from_attributes = True\n\n\n"
            f"class {class_name}CreateSchema(BaseModel):\n"
            f'    """Schema for creating a {class_name}."""\n\n'
            f"{create_fields}\n\n\n"
            f"# CRUD endpoint templates\n"
            f"# Prefix: /api/{base_name}\n"
            f"#\n"
            f"# GET    /api/{base_name}          # List (with pagination, filtering, sorting)\n"
            f"# POST   /api/{base_name}          # Create\n"
            f"# GET    /api/{base_name}/{{{pk_name}}}  # Read by ID\n"
            f"# PUT    /api/{base_name}/{{{pk_name}}}  # Full update\n"
            f"# PATCH  /api/{base_name}/{{{pk_name}}}  # Partial update\n"
            f"# DELETE /api/{base_name}/{{{pk_name}}}  # Delete\n\n\n"
            f"def register_{base_name}_routes(router: Any) -> None:\n"
            f'    """Register CRUD routes for {base_name}."""\n'
            f"    pass\n"
        )

        return {f"api_{base_name}.py": content}


def _type(field: CanonicalField) -> str:
    m = {"string": "str", "integer": "int", "float": "float", "boolean": "bool",
         "datetime": "str", "text": "str", "email": "str", "url": "str",
         "json": "Dict[str, Any]", "array": "list", "decimal": "float",
         "relation": "int"}
    return m.get(field.native_type, "Any")
