"""ubwenge — AI embedding metadata generator.

Produces embedding configuration, vector index definitions,
semantic search mappings, and RAG pipeline configuration
from a CanonicalModel.
"""

from __future__ import annotations

import json
from typing import Any, Dict, List

from ububiko.ihuriro.ibyara import BaseGenerator
from ububiko.ihuriro.ihuriro import CanonicalField, CanonicalModel


def _embedding_fields(model: CanonicalModel) -> List[CanonicalField]:
    """Return fields marked for embedding, falling back to text/string fields."""
    explicit = model.embed_fields
    if explicit:
        return explicit
    return [f for f in model.fields.values()
            if f.native_type in ("text", "string", "email", "url")
            and not f.secret][:3]


class EmbeddingGenerator(BaseGenerator):
    """Generates AI embedding configuration and vector index definitions."""

    target_name = "embeddings"

    @classmethod
    def generate(cls, model: CanonicalModel) -> Dict[str, str]:
        base_name = model.table_name
        class_name = model.name
        embed_fields = _embedding_fields(model)

        embedding_config = {
            "model": class_name,
            "table": base_name,
            "embedding_fields": [f.name for f in embed_fields],
            "dimensions": 384,
            "metric": "cosine",
            "auto_generate": True,
            "search_fields": [f.name for f in model.fields.values()
                              if f.indexed or f.name in ("name", "title", "description")][:3],
            "filter_fields": [f.name for f in model.fields.values()
                              if f.native_type in ("boolean",) or f.name in ("status", "active", "category_id")],
            "metadata_fields": [f.name for f in model.fields.values()
                                if not f.secret and f.native_type not in ("text", "blob", "password")][:10],
        }

        if embed_fields:
            embed_text = " + \"\\n\" + ".join(
                f"record.get('{f.name}', '')" for f in embed_fields
            )
        else:
            embed_text = "''"

        # Python embedding pipeline
        py_content = (
            f'"""AI embedding configuration for {class_name}.\n\n'
            f"Auto-generated by IHuriro.\n"
            f'"""\n\n'
            f"from typing import Any, Dict, List, Optional\n\n\n"
            f"EMBEDDING_CONFIG = {json.dumps(embedding_config, indent=2, default=str)}\n\n\n"
            f"def build_embedding_text(record: Dict[str, Any]) -> str:\n"
            f'    """Build the text to embed from a record."""\n'
            f"    return {embed_text}\n\n\n"
            f"def index_for_{base_name}(adapter: Any, embedding_service: Any, records: List[Dict[str, Any]]) -> int:\n"
            f'    """Index records for vector search."""\n'
            f"    count = 0\n"
            f"    for record in records:\n"
            f"        text = build_embedding_text(record)\n"
            f"        vector = embedding_service.embed(text)\n"
            f"        adapter.execute('insert', {{\n"
            f"            'vector': vector,\n"
            f"            'metadata': {{\n"
            f"                'id': record.get('id'),\n"
            f"{chr(10).join(f'                {f.name!r}: record.get({f.name!r}),' for f in model.fields.values() if not f.secret)[:5]}"
            f"            }},\n"
            f"        }})\n"
            f"        count += 1\n"
            f"    return count\n\n\n"
            f"def search_{base_name}(adapter: Any, embedding_service: Any, query: str, top_k: int = 10) -> List[Dict[str, Any]]:\n"
            f'    """Semantic search across {class_name} records."""\n'
            f"    vector = embedding_service.embed(query)\n"
            f"    results = adapter.execute('search', {{\n"
            f"        'vector': vector,\n"
            f"        'top_k': top_k,\n"
            f"    }})\n"
            f"    return [dict(r) for r in results]\n"
        )

        return {
            f"embeddings_{base_name}.json": json.dumps(embedding_config, indent=2, default=str),
            f"embeddings_{base_name}.py": py_content,
        }
