"""urutonde — Serialization generator.

Produces JSON Schema, Python serialization/deserialization functions,
and type conversion utilities from a CanonicalModel.
"""

from __future__ import annotations

import json
from typing import Any, Dict, List

from ububiko.ihuriro.ibyara import BaseGenerator
from ububiko.ihuriro.ihuriro import CanonicalField, CanonicalModel


def _json_schema_type(field: CanonicalField) -> Dict[str, Any]:
    mapping = {
        "string": {"type": "string"},
        "integer": {"type": "integer"},
        "float": {"type": "number"},
        "boolean": {"type": "boolean"},
        "datetime": {"type": "string", "format": "date-time"},
        "date": {"type": "string", "format": "date"},
        "uuid": {"type": "string", "format": "uuid"},
        "text": {"type": "string"},
        "email": {"type": "string", "format": "email"},
        "url": {"type": "string", "format": "uri"},
        "json": {"type": "object"},
        "array": {"type": "array"},
        "decimal": {"type": "number"},
        "relation": {"type": "integer"},
        "blob": {"type": "string"},
        "password": {"type": "string"},
    }
    schema = mapping.get(field.native_type, {"type": "string"})
    if field.max_length:
        schema["maxLength"] = field.max_length
    if field.min_value is not None:
        schema["minimum"] = field.min_value
    if field.max_value is not None:
        schema["maximum"] = field.max_value
    if field.description:
        schema["description"] = field.description
    if field.example is not None:
        schema["example"] = field.example
    if field.choices:
        schema["enum"] = [c[0] for c in field.choices]
    return schema


class SerializationGenerator(BaseGenerator):
    """Generates JSON Schema and Python serialization code."""

    target_name = "serialization"

    @classmethod
    def generate(cls, model: CanonicalModel) -> Dict[str, str]:
        base_name = model.table_name
        class_name = model.name

        # JSON Schema
        properties = {}
        required = []
        for f in model.fields.values():
            properties[f.name] = _json_schema_type(f)
            if f.required and not f.primary_key and not f.auto_increment:
                required.append(f.name)

        json_schema = {
            "$schema": "http://json-schema.org/draft-07/schema#",
            "title": class_name,
            "description": model.description or f"Schema for {class_name}",
            "type": "object",
            "properties": properties,
            "required": required,
        }
        if model.pk_field:
            json_schema["x-primary-key"] = model.pk_field.name

        schema_json = json.dumps(json_schema, indent=2, default=str)

        # Python serialization module
        py_content = (
            f'"""Serialization for {class_name}.\n\n'
            f"Auto-generated by IHuriro.\n"
            f'"""\n\n'
            f"import json\n"
            f"from datetime import datetime, date\n"
            f"from typing import Any, Dict, List, Optional\n\n\n"
            f"JSON_SCHEMA = {json.dumps(json_schema, indent=2, default=str)}\n\n\n"
            f"def to_dict(instance: Any) -> Dict[str, Any]:\n"
            f'    """Serialize a {class_name} instance to a dictionary."""\n'
            f"    result: Dict[str, Any] = {{}}\n"
        )

        for f in model.fields.values():
            if f.native_type == "datetime":
                py_content += (
                    f"    if hasattr(instance, '{f.name}'):\n"
                    f"        val = instance.{f.name}\n"
                    f"        result['{f.name}'] = val.isoformat() if hasattr(val, 'isoformat') else val\n"
                )
            elif f.native_type == "date":
                py_content += (
                    f"    if hasattr(instance, '{f.name}'):\n"
                    f"        val = instance.{f.name}\n"
                    f"        result['{f.name}'] = str(val)\n"
                )
            elif f.native_type == "json":
                py_content += (
                    f"    if hasattr(instance, '{f.name}'):\n"
                    f"        result['{f.name}'] = instance.{f.name}\n"
                )
            else:
                py_content += (
                    f"    if hasattr(instance, '{f.name}'):\n"
                    f"        result['{f.name}'] = instance.{f.name}\n"
                )

        py_content += (
            f"    return result\n\n\n"
            f"def from_dict(data: Dict[str, Any]) -> Dict[str, Any]:\n"
            f'    """Deserialize and validate a dictionary for {class_name}."""\n'
            f"    result: Dict[str, Any] = {{}}\n"
            f"    for key in {list(model.fields.keys())!r}:\n"
            f"        if key in data:\n"
            f"            result[key] = data[key]\n"
            f"    return result\n\n\n"
            f"def to_json(instance: Any, indent: int = 2) -> str:\n"
            f'    """Serialize a {class_name} instance to JSON."""\n'
            f"    return json.dumps(to_dict(instance), indent=indent, default=str, ensure_ascii=False)\n"
        )

        return {
            f"{base_name}.schema.json": schema_json,
            f"serialize_{base_name}.py": py_content,
        }
