"""Amategeko — CLI commands for MOBILE."""

from __future__ import annotations

import argparse
import os
import sys
from typing import Any


def kongera_iyobokamana(subparsers: Any) -> None:
    """Register mobile CLI subparsers."""
    mob_parser = subparsers.add_parser(
        "mobile",
        help="Mobile framework commands",
        description="Mobile framework commands for the I Programming Language",
    )

    mob_sub = mob_parser.add_subparsers(
        dest="mobile_command",
        help="Mobile subcommands",
        metavar="MOBILE_COMMAND",
    )

    p_gushya = mob_sub.add_parser(
        "gushya",
        help="Create a new mobile project",
    )
    p_gushya.add_argument("izina", help="Name of the mobile project")
    p_gushya.set_defaults(mobile_func=_gushya)

    p_genda = mob_sub.add_parser(
        "genda",
        help="Run a mobile app",
    )
    p_genda.add_argument("inzira", help="Path to .i file")
    p_genda.set_defaults(mobile_func=_genda)

    p_kubaka = mob_sub.add_parser(
        "kubaka",
        help="Build the project",
    )
    p_kubaka.add_argument("inzira", nargs="?", default=".", help="Path to project")
    p_kubaka.set_defaults(mobile_func=_kubaka)

    p_gupakira = mob_sub.add_parser(
        "gupakira",
        help="Package the app (apk/aab/ipa/debug)",
    )
    p_gupakira.add_argument("imiterere", choices=["apk", "aab", "ipa", "debug"], help="Package format")
    p_gupakira.set_defaults(mobile_func=_gupakira)

    p_emulator = mob_sub.add_parser(
        "emulator",
        help="Launch emulator",
    )
    p_emulator.add_argument("ikinyabiziga", choices=["android", "ios"], help="Target platform")
    p_emulator.set_defaults(mobile_func=_emulator)

    p_isuzuma = mob_sub.add_parser(
        "isuzuma",
        help="Doctor/diagnostics",
    )
    p_isuzuma.add_argument("inzira", nargs="?", default=".", help="Path to project")
    p_isuzuma.set_defaults(mobile_func=_isuzuma)

    p_profiler = mob_sub.add_parser(
        "profiler",
        help="Profile the app",
    )
    p_profiler.set_defaults(mobile_func=_profiler)

    p_ingingo = mob_sub.add_parser(
        "ingingo",
        help="List available components",
    )
    p_ingingo.set_defaults(mobile_func=_ingingo)

    p_gufasha = mob_sub.add_parser(
        "gufasha",
        help="Show mobile help",
    )
    p_gufasha.set_defaults(mobile_func=_gufasha)


def genda(args: argparse.Namespace) -> int:
    """Main dispatch function for mobile commands."""
    if not hasattr(args, "mobile_func"):
        print("Usage: isoko mobile <command> [options]")
        print()
        print("Available commands:")
        print("  gushya <izina>       Create a new mobile project")
        print("  genda <inzira.i>     Run a mobile app")
        print("  kubaka [inzira]      Build the project")
        print("  gupakira <imiterere> Package (apk/aab/ipa/debug)")
        print("  emulator <platform>  Launch emulator (android/ios)")
        print("  isuzuma [inzira]     Doctor/diagnostics")
        print("  profiler             Profile app")
        print("  ingingo              List available components")
        print("  gufasha              Show this help")
        return 0

    return args.mobile_func(args)


# ---------------------------------------------------------------------------
# Command implementations
# ---------------------------------------------------------------------------


def _gushya(args: argparse.Namespace) -> int:
    """Create a new mobile project with a complete .i file template."""
    izina = args.izina
    inzira = os.path.join(os.getcwd(), izina)

    try:
        os.makedirs(inzira, exist_ok=True)
    except OSError as e:
        print(f"Error creating directory: {e}")
        return 1

    content = (
        f'# {izina} - Mobile App\n'
        f'# Auto-generated by isoko mobile gushya\n'
        f'\n'
        f'# Imports for all mobile components\n'
        f'import mobile.porogaramu\n'
        f'import mobile.ikiganiro\n'
        f'import mobile.ubugenzuzi\n'
        f'import mobile.ibikoresho.buto\n'
        f'import mobile.ibikoresho.ikimenyetso\n'
        f'import mobile.ibikoresho.ifishi\n'
        f'import mobile.ibikoresho.ikarita\n'
        f'import mobile.ibikoresho.ishusho\n'
        f'import mobile.imiterere.inkingi\n'
        f'import mobile.imiterere.umurongo\n'
        f'import mobile.imiterere.urusobete\n'
        f'import mobile.imiterere.itemba\n'
        f'import mobile.kamere.imiterere\n'
        f'import mobile.kamere.ibonwa\n'
        f'\n'
        f'# Activity setup\n'
        f'activity Inyandikorero extends Ikiganiro:\n'
        f'    izina: "{izina}"\n'
        f'    urugero: "https://i-lang.rw/app"\n'
        f'\n'
        f'    onCreate:\n'
        f'        self.title = "Murakaza neza"\n'
        f'        ibara = Ibara("Kanda buto kugirango utangire")\n'
        f'        buto = Buto(\n'
        f'            text="Tangira",\n'
        f'            variant=ButoVariant.PRIMARY,\n'
        f'            on_press=lambda: self.on_buto_kanda(),\n'
        f'        )\n'
        f'        inkingi = Inkingi(\n'
        f'            children=[ibara, buto],\n'
        f'            spacing=16,\n'
        f'            padding=24,\n'
        f'            alignment=Alignment.CENTER,\n'
        f'        )\n'
        f'        self.set_content(inkingi)\n'
        f'\n'
        f'    on_buto_kanda:\n'
        f'        self.title = "Watangiye!"\n'
        f'\n'
        f'# Navigation setup\n'
        f'ubugenzuzi = Ubugenzuzi()\n'
        f'ubugenzuzi.register_route(NavigationRoute(\n'
        f'    path="/home",\n'
        f'    name="home",\n'
        f'    params={"title": "Ahabanza"},\n'
        f'))\n'
        f'ubugenzuzi.register_route(NavigationRoute(\n'
        f'    path="/profile/:id",\n'
        f'    name="profile",\n'
        f'    animation="slide_from_right",\n'
        f'))\n'
        f'\n'
        f'# Sample UI with Column, Button, Text\n'
        f'inkingi = Inkingi(\n'
        f'    spacing=12,\n'
        f'    padding=16,\n'
        f'    alignment=Alignment.CENTER,\n'
        f')\n'
        f'umutwe = Umutwe("Murakaza neza", level=1)\n'
        f'ibara = Ibara("Iyi ni mobile app yawe ya mbere mu rurimi rw\'I.")\n'
        f'buto = Buto("Kanda hano", variant=ButoVariant.PRIMARY)\n'
        f'inkingi.add(umutwe)\n'
        f'inkingi.add(ibara)\n'
        f'inkingi.add(buto)\n'
        f'\n'
        f'# State management example\n'
        f'imibare = Imiterere(0)\n'
        f'\n'
        f'def ku_mibare_hinduka(old, new):\n'
        f'    print(f"Imibare yahindutse: {old} -> {new}")\n'
        f'\n'
        f'id = imibare.observe(ku_mibare_hinduka)\n'
        f'imibare.set(1)\n'
        f'imibare.set(5)\n'
        f'\n'
        f'# Reactive observable example\n'
        f'izina_ribonwa = Ibonwa("{izina}")\n'
        f'izina_ribonwa.when(\n'
        f'    condition=lambda v: len(v) > 0,\n'
        f'    callback=lambda v: print(f"Izina: {v}"),\n'
        f')\n'
        f'\n'
        f'# Application entry point\n'
        f'app = MobileApplication("{izina}", version="1.0.0")\n'
        f'app.register_activity(Inyandikorero())\n'
        f'app.run()\n'
    )

    filepath = os.path.join(inzira, f"{izina}.i")
    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Created mobile project: {filepath}")
        return 0
    except OSError as e:
        print(f"Error writing file: {e}")
        return 1


def _genda(args: argparse.Namespace) -> int:
    """Run a mobile .i file."""
    inzira = args.inzira
    if not os.path.isfile(inzira):
        print(f"File not found: {inzira}")
        return 1
    print(f"Running mobile app: {inzira}")
    print("[MOBILE] App started (simulated — runtime pending)")
    return 0


def _kubaka(args: argparse.Namespace) -> int:
    """Build the project."""
    print(f"Building mobile project at: {args.inzira}")
    print("[MOBILE] Build complete (simulated)")
    return 0


def _gupakira(args: argparse.Namespace) -> int:
    """Package the app."""
    print(f"Packaging mobile app as {args.imiterere}...")
    print(f"[MOBILE] Package created: app.{args.imiterere} (simulated)")
    return 0


def _emulator(args: argparse.Namespace) -> int:
    """Launch an emulator."""
    ikinyabiziga = args.ikinyabiziga
    print(f"Launching {ikinyabiziga} emulator...")
    print(f"[MOBILE] {ikinyabiziga.capitalize()} emulator started (simulated)")
    return 0


def _isuzuma(args: argparse.Namespace) -> int:
    """Run diagnostics on a project."""
    import platform
    import shutil

    print("MOBILE Doctor / Diagnostics")
    print("=" * 40)
    print(f"Project path:      {os.path.abspath(args.inzira)}")
    print(f"Python version:    {platform.python_version()}")
    print(f"Platform:          {platform.system()} {platform.release()}")
    print(f"Node (for JS):     {shutil.which('node') or 'not found'}")
    print(f"Java (for Android): {shutil.which('java') or 'not found'}")
    print(f"Xcode (for iOS):   {'found' if platform.system() == 'Darwin' else 'not available'}")
    print("=" * 40)
    return 0


def _profiler(args: argparse.Namespace) -> int:
    """Profile the app."""
    print("Profiling mobile app...")
    print("[MOBILE] Profile data collected (simulated)")
    return 0


def _ingingo(args: argparse.Namespace) -> int:
    """List available mobile components."""
    components = [
        ("porogaramu", "MobileApplication — app lifecycle manager"),
        ("ikiganiro", "Ikiganiro — activity/screen management"),
        ("ubugenzuzi", "Ubugenzuzi — navigation system"),
        ("ibikoresho.buto", "Buto — button component"),
        ("ibikoresho.ikimenyetso", "Ikimenyetso / Umutwe / Ibara — text components"),
        ("ibikoresho.ifishi", "Ifishi — form input components"),
        ("ibikoresho.ikarita", "Ikarita — card component"),
        ("ibikoresho.ishusho", "Ishusho — image component"),
        ("ibikoresho.ikadiri", "Ikadiri — dialog components"),
        ("ibikoresho.ikubaza", "Ikubaza — bottom sheet components"),
        ("ibikoresho.umubare", "Umubare — number/badge components"),
        ("ibikoresho.urutonde", "Urutonde — list components"),
        ("imiterere.inkingi", "Inkingi — column layout"),
        ("imiterere.umurongo", "Umurongo — row layout"),
        ("imiterere.urusobete", "Urusobete — grid layout"),
        ("imiterere.itemba", "Itemba — table layout"),
        ("imiterere.ikinyabiziga", "Ikinyabiziga — scrollable container"),
        ("kamere.imiterere", "Imiterere — generic state container"),
        ("kamere.ibonwa", "Ibonwa / IbonwaOrutonde / IbonwaInzuzi — reactive state"),
        ("kamere.ubuzima", "Ubuzima — lifecycle-aware state management"),
    ]
    print("Available MOBILE components:")
    print()
    for path, desc in components:
        print(f"  {path:35s} {desc}")
    return 0


def _gufasha(args: argparse.Namespace) -> int:
    """Show detailed mobile help."""
    print("isoko mobile — Mobile Framework Commands")
    print()
    print("USAGE")
    print("  isoko mobile <command> [options]")
    print()
    print("COMMANDS")
    print("  gushya <izina>         Create a new mobile project with template")
    print("  genda <inzira.i>       Run a mobile app from .i file")
    print("  kubaka [inzira]        Build the mobile project")
    print("  gupakira <imiterere>   Package the app (apk, aab, ipa, debug)")
    print("  emulator <ikinyabiziga> Launch emulator (android, ios)")
    print("  isuzuma [inzira]       Run diagnostics on the project")
    print("  profiler               Profile the application")
    print("  ingingo                List all available mobile components")
    print("  gufasha                Show this help message")
    print()
    print("EXAMPLES")
    print("  isoko mobile gushya myapp         Create a new project")
    print("  isoko mobile genda main.i        Run an app")
    print("  isoko mobile kubaka              Build current project")
    print("  isoko mobile gupakira apk        Package as APK")
    print("  isoko mobile emulator android    Launch Android emulator")
    print("  isoko mobile isuzuma             Check environment")
    print("  isoko mobile ingingo             List components")
    return 0
