"""
AST package for the I programming language.

This package contains the abstract syntax tree node definitions,
visitor implementations, validators, serializers, and visualizers.
"""

from compiler.ast.nodes import (
    # Enums
    NodeType,
    # Location & ID
    SourceLocation,
    # Base classes
    ASTNode,
    Expr,
    Stmt,
    Decl,
    TypeNode,
    ASTVisitor,
    # Expressions
    LiteralExpr,
    IdentifierExpr,
    UnaryExpr,
    BinaryExpr,
    LogicalExpr,
    AssignmentExpr,
    CompoundAssignmentExpr,
    CallExpr,
    MethodCallExpr,
    ConstructorExpr,
    GetExpr,
    SetExpr,
    IndexExpr,
    SliceExpr,
    SelfExpr,
    SuperExpr,
    ListExpr,
    DictExpr,
    TupleExpr,
    LambdaExpr,
    IfExpr,
    GroupingExpr,
    PlaceholderExpr,
    # Type nodes
    NamedType,
    GenericType,
    FunctionType,
    OptionalType,
    TupleType,
    # Declarations
    VarDecl,
    FunctionDecl,
    MethodDecl,
    StructDecl,
    EnumDecl,
    ClassDecl,
    TraitDecl,
    InterfaceDecl,
    ImportDecl,
    ExportDecl,
    # Statements
    BlockStmt,
    IfStmt,
    WhileStmt,
    UntilStmt,
    ForStmt,
    ForEachStmt,
    ReturnStmt,
    BreakStmt,
    ContinueStmt,
    ThrowStmt,
    TryStmt,
    ExpressionStmt,
    EmptyStmt,
    # Helpers
    Parameter,
    StructField,
    EnumVariant,
    ElifBranch,
    # Root
    Program,
    Module,
)

__all__ = [
    # Enums
    'NodeType',
    # Location & ID
    'SourceLocation',
    # Base classes
    'ASTNode',
    'Expr',
    'Stmt',
    'Decl',
    'TypeNode',
    'ASTVisitor',
    # Expressions
    'LiteralExpr',
    'IdentifierExpr',
    'UnaryExpr',
    'BinaryExpr',
    'LogicalExpr',
    'AssignmentExpr',
    'CompoundAssignmentExpr',
    'CallExpr',
    'MethodCallExpr',
    'ConstructorExpr',
    'GetExpr',
    'SetExpr',
    'IndexExpr',
    'SliceExpr',
    'SelfExpr',
    'SuperExpr',
    'ListExpr',
    'DictExpr',
    'TupleExpr',
    'LambdaExpr',
    'IfExpr',
    'GroupingExpr',
    'PlaceholderExpr',
    # Type nodes
    'NamedType',
    'GenericType',
    'FunctionType',
    'OptionalType',
    'TupleType',
    # Declarations
    'VarDecl',
    'FunctionDecl',
    'MethodDecl',
    'StructDecl',
    'EnumDecl',
    'ClassDecl',
    'TraitDecl',
    'InterfaceDecl',
    'ImportDecl',
    'ExportDecl',
    # Statements
    'BlockStmt',
    'IfStmt',
    'WhileStmt',
    'UntilStmt',
    'ForStmt',
    'ForEachStmt',
    'ReturnStmt',
    'BreakStmt',
    'ContinueStmt',
    'ThrowStmt',
    'TryStmt',
    'ExpressionStmt',
    'EmptyStmt',
    # Helpers
    'Parameter',
    'StructField',
    'EnumVariant',
    'ElifBranch',
    # Root
    'Program',
    'Module',
]
